# Generated by Django 2.2.16 on 2022-04-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220408_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
